services:
  - type: web
    name: foodexpress-backend
    env: docker
    region: frankfurt # You can change this to 'oregon', 'ohio', or 'singapore' in the Render Dashboard
    plan: free
    dockerContext: backend/
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
